#!/usr/bin/env bash

cp .env.dev.sample .env.dev

docker-compose build

docker-compose run --rm web bundle exec rails new . --force --database=postgresql --skip-git --skip-test

cp -f template/database.yml config/database.yml

docker-compose run --rm web bundle exec rails db:create db:migrate
docker-compose run --rm web bundle exec spring binstub --all
